### ISSUE TITLE
Clarification about Point Cloud Generation

### ISSUE THREAD

**Issue by oaishi** [facebookresearch/synsin#12]
Hello. Thanks for the helpful repository. It is really insightful. I have just started to learn about Pytorch3D. I was a bit confused about the process of generating point cloud from the input image and generating an image from the point cloud again. I will be grateful if you kindly help me understand the codebase exactly where and how the point cloud is generated, re-rendered into an image and backpropagated.

**Comment by oawiles** [comment]
So probably two things are helpful:
1.  A basic example showing how to use point clouds in Pytorch3D: https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_colored_points.ipynb

2. The forward pass of the main model showing how the renderer, features, etc. are used together: https://github.com/facebookresearch/synsin/blob/master/models/z_buffermodel.py#L50

**Comment by oaishi** [comment]
Thank you so much!
