### ISSUE TITLE
How large is RealEstate10K dataset

### ISSUE THREAD

**Issue by phongnhhn92** [facebookresearch/synsin#13]
Hello,
This is not an issue about the code of SynSin but is a technical question related to RealEstate10K dataset. So I have been trying to train SynSin with this dataset and I have manage to train a small model with about 100 videos. The performance is far worse than the provided checkpoint but I would like to train with the whole dataset so I would like to ask how large is this RealEstate10K dataset.
I had a limit of 1TB storage in my own cloud server so I don't know whether if I can ever train SynSin on the whole dataset or not ^^

**Comment by oawiles** [comment]
Unfortunately RealEstate10K is very large (I think 7TB).

You could try to download as large a subset as fits on your computer.

**Comment by phongnhhn92** [comment]
Do you think it would affect the training results if I train the model with a subset of the whole data ? I am just afraid it would never be able to reach similar results with your provided checkpoint which has been trained on the whole dataset.

**Comment by oawiles** [comment]
I can't be sure -- It probably won't be as good as training with the whole dataset but would be much better than training with 100 videos

**Comment by phongnhhn92** [comment]
Thanks ! I will close this for now.
