### ISSUE TITLE
The content of image's txt file is different

### ISSUE THREAD

**Issue by Pabebezz** [facebookresearch/synsin#14]
hi,Thanks for you research.I have one question that I hope you can answer.
When I extract frames as your format,The content of image's txt file is different. 
Can you explain it?  I appreciate your help！

**for example**
you provide（https://raw.githubusercontent.com/facebookresearch/synsin/master/data/files/realestate.txt） :
000c3ab189999a83 49716333 49716333 123.477562 219.515671 128.0 128.0 0.994582 0.007716 -0.103669 0.066855 -0.007079 0.999954 0.006514 0.050014 0.103715 -0.005744 0.994591 -2.286677 0.994582 0.007716 -0.103669 0.066855 -0.007079 0.999954 0.006514 0.050014 0.103715 -0.005744 0.994591 -2.286677

the raw data（RealEstate10K/test/000c3ab189999a83.txt):
49716333 0.482334223 0.857483078 0.500000000 0.500000000 0.000000000 0.000000000 0.994581878 0.007715873 -0.103669293 0.066854894 -0.007078611 0.999953747 0.006513574 0.050014287 0.103714757 -0.005744448 0.994590521 -2.286676987

**Comment by phongnhhn92** [comment]
@Pabebezz I think the difference comes from the normalize step to convert the image coordinates from (0,W) and (0,H) to (-1,1). I am not sure because it looks like some numbers are being scaled now.

**Comment by oawiles** [comment]
Yes, the intrinsic camera parameters have been rescaled as @phongnhhn92 said

**Comment by Pabebezz** [comment]
I get it. Thank both of you！
@phongnhhn92 you are awesome
