### ISSUE TITLE
Functionality of learn_feature

### ISSUE THREAD

**Issue by oaishi** [facebookresearch/synsin#21]
Hello, in the z_buffer_layers.py class, there is an optional argument, **[learn_feature](https://github.com/facebookresearch/synsin/blob/master/models/layers/z_buffer_layers.py#L43)**. I was unsure about the functionality of this argument as it is commented out in the forward function. Can you kindly help me to understand this?

![1_learn_feature](https://user-images.githubusercontent.com/22328326/88459222-8c82b480-ceb5-11ea-96c7-7eb33ab5e11b.PNG)

![learn_feature](https://user-images.githubusercontent.com/22328326/88459187-40377480-ceb5-11ea-9a55-13233afd3ef0.PNG)

**Comment by oawiles** [comment]
The idea of having this additional feature was to allow the network to learn something other than all-zeros to fill in regions in the output image that were occluded in the original image. 

The inspiration came from Victor lempitsky's work on rendering (https://arxiv.org/abs/1906.08240). However, we didn't use this in the end, as it had limited value.

Hope that helps!

**Comment by oaishi** [comment]
Thank you so much for the clarification and sharing the related paper. It helped me a lot!
