### ISSUE TITLE
Neural point cloud renderer

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [facebookresearch/synsin#22]
Probably not an issue, it's more a clarification: can you point me to the neural point cloud renderer code in this repository, as described in the paper? The proposed solutions to naive rendering are very interesting, I'd like to explore them further in some other tasks.

**Comment by jcjohnson** [comment]
It's part of PyTorch3D:

C++ / CUDA core:
https://github.com/facebookresearch/pytorch3d/tree/master/pytorch3d/csrc/rasterize_points

Python interface:
https://github.com/facebookresearch/pytorch3d/tree/master/pytorch3d/renderer/points

**Comment by VitorGuizilini-TRI** [comment]
Thank you! My next question would have been if we can use non-square images, but apparently you are already working on it, so I guess that's all for now. :)
