### ISSUE TITLE
No Downloading Permission of a video

### ISSUE THREAD

**Issue by simon3dv** [facebookresearch/synsin#28]
I have downloaded all images following [realestate.txt](https://github.com/facebookresearch/synsin/blob/master/data/files/kitti.txt) except these files
```
00ae21ab50209282.txt  10eebcbb9021f437.txt  24ac24abf3057732.txt  2cf32e2408107ea7.txt  3916390b35258215.txt  44b2ab5292c06a7e.txt 
0a5e107e1961d01d.txt  23341c3a0b420e54.txt  2bd43375196ce1a7.txt  3172ad0d099430da.txt  416f82fdbad68e21.txt  477a0a9f77c00480.txt
```
I cannot get the videos of these files, because they all need [5uP-le4wTaM](https://www.youtube.com/watch?v=5uP-le4wTaM), but I have no permission of it. Can you provide it?
My email is 2017100101013@std.uestc.edu.cn

**Comment by gkioxari** [comment]
No no! We cannot provide any data that we don't have the permission for. Please contact the creators of the dataset.
