### ISSUE TITLE
--norm_G 'sync:spectral_batch'

### ISSUE THREAD

**Issue by tomguluson92** [facebookresearch/synsin#3]
Hi olivia:
    your work inspired me a lot! Thank you!
     Here I just wonder `--norm_G 'sync:spectral_batch'` in the `train.sh`, does it use for single GPU multiple Nvidia graphic cards? Which means if I want to test it on only one card, It's ok for me to change this to `--norm_G 'spectral_batch'`?
    Thank you!

**Comment by oawiles** [comment]
You can run on 1 GPU as is. no need to change.

**Comment by tomguluson92** [comment]
> You can run on 1 GPU as is. no need to change.

Thx
