### ISSUE TITLE
The installation doesn't work in conda.

### ISSUE THREAD

**Issue by OwenHua666** [facebookresearch/synsin#5]
`conda create –-name synsin_env –-file requirements.txt` gives the error: CondaValueError: The target prefix is the base prefix. Aborting.
I tried to install the required libs using virtual environment, but `import quaternion` fails and pytorch3d  also report an error.

**Comment by ilnmtlbnm** [comment]
Hey @OwenHua666, 

You need to install pytorch3d from the pytorch3d-nightly conda channel.

I had the same issue, and ended up creating a separated 'clean' environment.yml with all the dependencies : https://github.com/ilnmtlbnm/synsin/blob/master/environment.yml

You can just `conda env create -f environment.yml` then `conda activate synsin_env` and you're all set.

Don't forget to `bash download_models.sh`, the demos will work, from there you can start to dig deeper.

**Comment by oawiles** [comment]
Thanks for the help @ilnmtlbnm ! Hope that fixes your problem @OwenHua666

**Comment by OwenHua666** [comment]
I will try and let you guys know. Thanks a lot!

**Comment by marija-p** [comment]
> Hey @OwenHua666,
> 
> You need to install pytorch3d from the pytorch3d-nightly conda channel.
> 
> I had the same issue, and ended up creating a separated 'clean' environment.yml with all the dependencies : https://github.com/ilnmtlbnm/synsin/blob/master/environment.yml
> 
> You can just `conda env create -f environment.yml` then `conda activate synsin_env` and you're all set.
> 
> Don't forget to `bash download_models.sh`, the demos will work, from there you can start to dig deeper.

I had the same issue and can confirm that this helped. Thank you! 😊

**Comment by gkioxari** [comment]
Closing this issue as everything seems to be resolved. Feel free to re-open if anything new emerges.

**Comment by HarryShak** [comment]
Getting this error after I ran 'conda env create -f environment.yml'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\computers\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 81, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 43, in detect
        if spec.can_handle():
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\env.py", line 165, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\env.py", line 143, in from_yaml
        data = validate_keys(data, kwargs)
      File "C:\Users\computers\anaconda3\lib\site-packages\conda_env\env.py", line 38, in validate_keys
        for key in data.keys():
    AttributeError: 'NoneType' object has no attribute 'keys'

`$ C:\Users\computers\anaconda3\Scripts\conda-env-script.py create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_EXE=C:\Users\computers\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\computers\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\computers\anaconda3
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\computers
                     PATH=C:\Users\computers\anaconda3;C:\Users\computers\anaconda3\Library\ming
                          w-w64\bin;C:\Users\computers\anaconda3\Library\usr\bin;C:\Users\comput
                          ers\anaconda3\Library\bin;C:\Users\computers\anaconda3\Scripts;C:\User
                          s\computers\anaconda3\bin;C:\Program Files\Common
                          Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\
                          Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;
                          C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSS
                          H\;C:\hadoop\hadoop-3.2.1\bin;C:\Program
                          Files\Amazon\AWSCLIV2\;C:\Program Files\MATLAB\R2020b\bin;C:\Users\com
                          puters\anaconda3;C:\Users\computers\anaconda3\Library\mingw-w64\bin;C:
                          \Users\computers\anaconda3\Library\usr\bin;C:\Users\computers\anaconda
                          3\Library\bin;C:\Users\computers\anaconda3\Scripts;C:\Users\computers\
                          AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\computers\App
                          Data\Local\Programs\Python\Python36\;C:\Users\computers\AppData\Local\
                          Microsoft\WindowsApps;C:\PROGRA~1\Java\JDK18~1.0_2\bin;C:\Program
                          Files\JetBrains\PyCharm 2021.1\bin;C:\Program Files\JetBrains\PyCharm
                          Community Edition 2021.1\bin
             PSMODULEPATH=%ProgramFiles%\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPo
                          werShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\computers\.condarc
 populated config files : C:\Users\computers\.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\computers\anaconda3  (writable)
      conda av data dir : C:\Users\computers\anaconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\computers\anaconda3\pkgs
                          C:\Users\computers\.conda\pkgs
                          C:\Users\computers\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\computers\anaconda3\envs
                          C:\Users\computers\.conda\envs
                          C:\Users\computers\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
