### ISSUE TITLE
pre train weight download

### ISSUE THREAD

**Issue by JaeDukSeo** [facebookresearch/synsin#7]
the link does not work

**Comment by oawiles** [comment]
This is odd, as other people have managed to download the models.

**Comment by JaeDukSeo** [comment]
https://dl.fbaipublicfiles.com/synsin/checkpoints/readme.txt

I think the service is down, even wget does not work

**Comment by oawiles** [comment]
Maybe. I'm not at Facebook anymore -- so I can't check this. Hopefully it comes back up!

**Comment by gkioxari** [comment]
I can download all models.

**Comment by JaeDukSeo** [comment]
LOOOOL funny enough the ip must be US origin. Had to use a VPN XD

**Comment by gkioxari** [comment]
Oh hmm. I don't think the origin has to be US. But if it worked for ya, then we will embrace it!
